# 拦截器配置示例
xingge:
  interceptor:
    # 是否启用拦截器
    enabled: true
    
    # 全局配置
    global:
      # 是否记录请求体
      record-request-body: true
      # 是否记录响应体
      record-response-body: true
      # 线程池配置
      thread-pool:
        core-size: 5
        max-size: 20
        queue-capacity: 1000
        keep-alive-seconds: 60
        thread-name-prefix: "interceptor-"
    
    # 拦截器配置列表
    interceptors:
      # 外部请求拦截配置
      - intercept-type: request
        intercept-scope: external
        include-patterns:
          - "/api/**"
          - "/rest/**"
        exclude-patterns:
          - "/api/health"
          - "/api/actuator/**"
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        processors:
          # 日志记录处理器
          - type: log
            async: true
            config:
              level: INFO
              include-headers: true
              include-request-body: true
              include-response-body: true
              mdc-keys:
                - traceId
                - userId
                - tenantId
          
          # MySQL数据库处理器
          - type: mysql
            async: true
            config:
              table-name: http_request_log
              batch-size: 100
              custom-fields:
                app_name: "${applicationName}"
                env: "${spring.profiles.active}"
          
          # MongoDB处理器
          - type: mongo
            async: true
            config:
              collection-name: http_requests
              database-name: logs
              batch-size: 50
              create-index: true
              ttl-seconds: 2592000  # 30天
              custom-fields:
                source: external
                version: "1.0"
      
      # 内部请求拦截配置
      - intercept-type: request
        intercept-scope: internal
        include-patterns:
          - "http://*/api/**"
          - "https://*/api/**"
        exclude-patterns:
          - "**/health"
        processors:
          # 日志记录
          - type: log
            async: true
            config:
              level: DEBUG
              include-headers: false
              include-request-body: true
              include-response-body: false
          
          # PostgreSQL处理器
          - type: postgresql
            async: true
            config:
              table-name: internal_requests
              schema: logs
              batch-size: 200
              use-jsonb: true
              custom-fields:
                direction: outbound
          
          # RocketMQ处理器
          - type: rocketmq
            async: true
            config:
              topic: http-requests
              tag: internal
              producer-group: interceptor-producer
              name-server: localhost:9876
              send-timeout: 3000
              retry-times: 2
              message-format: json
              custom-properties:
                source: internal
                priority: normal

# 支持的HTTP客户端类型说明：
# 1. RestTemplate - Spring原生HTTP客户端，通过HttpClientInterceptor和HttpTemplateInterceptor拦截
# 2. OkHttp - 高性能HTTP客户端，通过OkHttpInterceptor拦截
# 3. Feign - 声明式HTTP客户端，通过FeignInterceptor拦截
# 4. HttpURLConnection - 原生Java HTTP客户端，通过HttpClientInterceptor拦截
#
# 拦截器会自动识别并处理不同类型的HTTP客户端请求
# 配置中的intercept-scope参数：
# - external: 拦截外部进入的HTTP请求（通过HttpRequestInterceptor）
# - internal: 拦截内部发出的HTTP请求（通过各种客户端拦截器）
# - all: 同时拦截外部和内部请求